config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'twitters/twitter_search'

  resources :twitter_accounts

  get 'dashboard/show'

  get 'twitter_accounts/refresh_button/:id' => 'twitter_accounts#refresh_button'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :twitter_account
  validates_associated :twitter_account
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets, dependent: :destroy
  validates_length_of :tweets, maximum: 10

  validate :twitter_accounts_limit, on: :create

  def twitter_accounts_limit
    if self.user.twitter_accounts.count >= 5
      errors.add(:base, "Only 5 Twitter Accounts allowed")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :twitter_accounts, dependent: :destroy  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @twitter_accounts = current_user.twitter_accounts
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController

  before_action :authenticate_user!

  def new
    @twitter_account = TwitterAccount.new
  end

  def create
    @twitter_account = TwitterAccount.new(twitter_account_params)
    @twitter_account.user_id = current_user.id
    if @twitter_account.save
      id = @twitter_account.id
      DeliverTweetsService.deliver_tweets(id)
      redirect_to @twitter_account
    else
      render :new
    end
  end

  def refresh_button
    @twitter_account = TwitterAccount.find(params[:id])
    id = @twitter_account.id
    DeliverTweetsService.deliver_tweets(id)
    redirect_to :back
  end

  def show
    @twitter_account = TwitterAccount.find(params[:id])
    @result = Tweet.where("twitter_account_id = ?", params[:id])
  end

  def destroy
    @twitter_account = TwitterAccount.find(params[:id])
    @twitter_account.destroy
    redirect_to :back
  end

private

  def twitter_account_params
    params.require(:twitter_account).permit(:name, :user_id)
  end

end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController

  def twitter_search
    if request.GET.include? "tag"
      tag = [params[:tag]]
      @search  = TwitterApi.client.search(tag.join(",")).take(10).collect
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>

<% @twitter_accounts.each do |twitter_account| %>
  <p>
    <%= link_to(twitter_account.name, twitter_account) %>
    <%= twitter_account.tweets.first.try(:text) %>
    <%= link_to 'Destroy', twitter_account, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<%= link_to('New Twitter account', new_twitter_account_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclient</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twitter_accounts/_tweets_list.html.erb
<% @result.each  do |tweet| %>
  <p>
    <%= tweet.text%>
  </p>
<% end %>

app/views/twitter_accounts/new.html.erb
<h1>TwitterAccounts#new</h1>
<p>Find me in app/views/twitter_accounts/new.html.erb</p>
<% if @twitter_account.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@twitter_account.errors.count, "error") %> prohibited this Twitter account from being saved:</h2>
    <ul>
    <% @twitter_account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(@twitter_account) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

<%= link_to('Dashboard', dashboard_show_path) %>

app/views/twitter_accounts/show.html.erb
<h1>TwitterAccounts#show</h1>

<% if @twitter_account.name %>
  <%= @twitter_account.name %>
    <%= render partial: 'tweets_list' %>
  <% end %>

<%= link_to('Refresh', controller: 'twitter_accounts', action:'refresh_button', id:@twitter_account.id ) %>
<%= link_to('Dashboard', dashboard_show_path) %>

app/views/twitters/_tweets_list.html.erb
<% @search.each do |tweet| %>
  <p>
    <%= image_tag(tweet.user.profile_image_url) %>
      <%= tweet.user.name %>
      <%= tweet.text %>
  </p>
<% end %>

app/views/twitters/twitter_search.html.erb
<form>
  <p>
    <input name="tag" id="tag" placeholder="Provide tags with # here">
    <button type="submit" class="">Search</button>
  </p>
</form>

<% if request.GET.include? "tag" %>
  <%= render 'tweets_list' %>
<% end %>